import SwiftUI

struct AccountView: View {
    @EnvironmentObject private var app: AppContainer
    @EnvironmentObject private var auth: AuthStore
    @State private var profile = [String: JSONValue]()
    @State private var name = ""; @State private var phone = ""; @State private var avatar = ""
    @State private var error = ""; @State private var notice = ""
    let open: (Route) -> Void
    var body: some View { AFScreen { ScrollView { VStack(alignment: .leading, spacing: 18) { profileHero; if !error.isEmpty { feedback(error, color: .red) }; if !notice.isEmpty { feedback(notice, color: .green) }; profileEditor; actionGroup("Cumpărător", items: [("Favorite", "heart", { open(.collection(.favorites)) }), ("Căutări salvate", "bookmark", { open(.collection(.saved)) }), ("Alerte", "bell", { open(.collection(.notifications)) }), ("Mesaje", "message", { open(.messages) })]); sellerGroup; Button("Deconectare", role: .destructive) { Task { await auth.signOut() } }.font(.subheadline.weight(.bold)).frame(maxWidth: .infinity).padding(.vertical, 14) }.padding(20) } }.navigationTitle("Cont") .task { await load() } }
    private var profileHero: some View { AFCard { HStack(spacing: 14) { Image(systemName: "person.fill").font(.title2).foregroundStyle(AFTheme.paper).frame(width: 56, height: 56).background(AFTheme.graphite).clipShape(Circle()); VStack(alignment: .leading, spacing: 4) { Text(name.isEmpty ? "Profilul tău" : name).font(.title3.weight(.bold)).foregroundStyle(AFTheme.ink); Text(profile[string: "email"]).font(.subheadline).foregroundStyle(AFTheme.muted); Label(profile[string: "role"] == "seller" ? (profile[bool: "is_verified"] ? "Vânzător verificat" : "Vânzător") : "Cumpărător", systemImage: profile[bool: "is_verified"] ? "checkmark.seal.fill" : "person").font(.caption.weight(.bold)).foregroundStyle(profile[bool: "is_verified"] ? .green : AFTheme.gold) }; Spacer() } } }
    private var profileEditor: some View { AFCard { VStack(alignment: .leading, spacing: 12) { Text("Date personale").font(.headline.weight(.bold)).foregroundStyle(AFTheme.ink); field("Nume afișat", $name); field("Telefon", $phone, keyboard: .phonePad); field("URL avatar (opțional)", $avatar); Button("Salvează modificările") { call("update_profile", ["displayName": .string(name), "phone": .string(phone), "avatarUrl": .string(avatar)]) }.buttonStyle(AFPrimaryButton()) } } }
    private func actionGroup(_ title: String, items: [(String, String, () -> Void)]) -> some View { AFCard { VStack(alignment: .leading, spacing: 3) { Text(title).font(.headline.weight(.bold)).foregroundStyle(AFTheme.ink).padding(.bottom, 5); ForEach(items.indices, id: \.self) { index in let item = items[index]; Button(action: item.2) { HStack { Image(systemName: item.1).foregroundStyle(AFTheme.gold).frame(width: 25); Text(item.0).font(.subheadline.weight(.semibold)).foregroundStyle(AFTheme.ink); Spacer(); Image(systemName: "chevron.right").font(.caption.bold()).foregroundStyle(AFTheme.muted) }.padding(.vertical, 10).contentShape(Rectangle()) }; if index < items.count - 1 { Divider() } } } } }
    @ViewBuilder private var sellerGroup: some View { if profile[string: "role"] == "seller" { actionGroup("Vânzător", items: [("Creează anunț", "plus.circle", { open(.listingEditor(nil)) }), ("Anunțurile mele", "car.2", { open(.sellerListings) }), ("Dashboard seller", "chart.bar", { open(.sellerDashboard) })]) } else { AFCard { VStack(alignment: .leading, spacing: 10) { Label("Vinde pe AutoFans", systemImage: "sparkles").font(.headline.weight(.bold)).foregroundStyle(AFTheme.ink); Text("Publică, gestionează și răspunde cumpărătorilor direct din aplicație.").font(.subheadline).foregroundStyle(AFTheme.muted); Button("Devino vânzător") { call("promote_seller") }.buttonStyle(AFGoldButton()) } } } }
    private func field(_ title: String, _ binding: Binding<String>, keyboard: UIKeyboardType = .default) -> some View { TextField(title, text: binding).keyboardType(keyboard).padding(12).background(AFTheme.ivory).clipShape(RoundedRectangle(cornerRadius: 12)) }
    private func feedback(_ text: String, color: Color) -> some View { Text(text).font(.footnote.weight(.semibold)).foregroundStyle(color).padding(12).frame(maxWidth: .infinity, alignment: .leading).background(color.opacity(0.08)).clipShape(RoundedRectangle(cornerRadius: 12)) }
    private func load() async { do { setProfile(try await app.api.call("account")["profile"]?.object ?? [:]) } catch { self.error = error.localizedDescription } }
    private func setProfile(_ profile: [String: JSONValue]) { self.profile = profile; name = profile[string: "display_name"]; phone = profile[string: "phone"]; avatar = profile[string: "avatar_url"] }
    private func call(_ operation: String, _ payload: [String: JSONValue] = [:]) { Task { do { let result = try await app.api.call(operation, payload: payload); if operation == "update_profile", let profile = result["profile"]?.object { setProfile(profile); notice = "Profil actualizat." } else if operation == "promote_seller" { notice = "Cont promovat la vânzător."; await load() } else { notice = "Solicitarea a fost trimisă." } } catch { self.error = error.localizedDescription } } }
}

struct CollectionView: View {
    @EnvironmentObject private var app: AppContainer
    @State private var rows = [[String: JSONValue]](); @State private var error = ""; @State private var edit: [String: JSONValue]?; @State private var name = ""
    let kind: CollectionKind; let open: (Route) -> Void
    var body: some View { AFScreen { ScrollView { VStack(alignment: .leading, spacing: 15) { Text(kind.title).font(.system(size: 30, weight: .bold, design: .rounded)).foregroundStyle(AFTheme.ink); if !error.isEmpty { Text(error).foregroundStyle(.red) }; if rows.isEmpty && error.isEmpty { AFCard { AFEmptyState(icon: kind == .favorites ? "heart" : "tray", title: "Nu există elemente încă", detail: "Când vei avea activitate, o vei găsi aici.") } }; ForEach(Array(rows.enumerated()), id: \.offset) { _, row in rowView(row) } }.padding(20) } }.navigationTitle(kind.title).task { await load() }.alert("Redenumește căutarea", isPresented: Binding(get: { edit != nil }, set: { if !$0 { edit = nil } })) { TextField("Nume", text: $name); Button("Salvează") { if let id = edit?[int: "id"] { perform("update_saved_search", ["id": .number(Double(id)), "name": .string(name)]) }; edit = nil }; Button("Renunță", role: .cancel) { edit = nil } } }
    @ViewBuilder private func rowView(_ row: [String: JSONValue]) -> some View { let listing = row["listings"]?.object ?? row["listings"]?.array?.first?.object; AFCard { VStack(alignment: .leading, spacing: 8) { Text(kind == .favorites ? (listing?[string: "title"] ?? "Anunț indisponibil") : (kind == .saved ? row[string: "name"] : row[string: "title"])).font(.headline.weight(.bold)).foregroundStyle(AFTheme.ink); if kind == .favorites { Text("\(listing?[string: "price"] ?? "") \(listing?[string: "currency"] ?? "EUR")").foregroundStyle(AFTheme.gold); if let slug = listing?[string: "slug"], !slug.isEmpty { Button("Deschide anunțul") { open(.listing(slug)) }.font(.subheadline.weight(.bold)).foregroundStyle(AFTheme.gold) } }; if let body = row["body"]?.string { Text(body).font(.subheadline).foregroundStyle(AFTheme.muted) }; if kind == .saved { HStack { Button("Redenumește") { edit = row; name = row[string: "name"] }; Button("Șterge", role: .destructive) { if let id = row[int: "id"] { perform("delete_saved_search", ["id": .number(Double(id))]) } } }.font(.caption.weight(.bold)) }; if kind == .notifications && row["read_at"] == .null, let id = row[int: "id"] { Button("Marchează citit") { perform("read_notification", ["id": .number(Double(id))]) }.font(.caption.weight(.bold)).foregroundStyle(AFTheme.gold) } } } }
    private func load() async { do { rows = try await app.api.call(kind.operation)[kind.key]?.array?.compactMap(\.object) ?? [] } catch { self.error = error.localizedDescription } }
    private func perform(_ operation: String, _ payload: [String: JSONValue]) { Task { do { _ = try await app.api.call(operation, payload: payload); await load() } catch { self.error = error.localizedDescription } } }
}

struct MessagesView: View {
    @EnvironmentObject private var app: AppContainer
    @State private var conversations = [[String: JSONValue]](); @State private var messages = [[String: JSONValue]](); @State private var activeID: Int?; @State private var draft = ""; @State private var error = ""
    var body: some View { AFScreen { VStack(spacing: 0) { if let active = activeID { conversation(active) } else { inbox } }.navigationTitle(activeID == nil ? "Mesaje" : "Conversație").task { await loadConversations() } } }
    private var inbox: some View { ScrollView { VStack(alignment: .leading, spacing: 14) { if conversations.isEmpty && error.isEmpty { AFCard { AFEmptyState(icon: "message", title: "Nicio conversație încă", detail: "Contactează un vânzător din pagina unui anunț.") } }; ForEach(conversations.indices, id: \.self) { index in let item = conversations[index]; Button { if let id = item[int: "id"] { activeID = id; Task { await loadMessages(id) } } } label: { AFCard { HStack { Image(systemName: "message.fill").foregroundStyle(AFTheme.gold); VStack(alignment: .leading, spacing: 3) { Text("Conversație pentru anunțul #\(item[string: "listing_id"])").font(.headline.weight(.bold)).foregroundStyle(AFTheme.ink); Text("Apasă pentru a continua discuția").font(.caption).foregroundStyle(AFTheme.muted) }; Spacer(); Image(systemName: "chevron.right").foregroundStyle(AFTheme.muted) } } } } }.padding(20) } }
    private func conversation(_ id: Int) -> some View { VStack(spacing: 0) { ScrollView { LazyVStack(alignment: .leading, spacing: 10) { ForEach(messages.indices, id: \.self) { index in let message = messages[index]; HStack { if index.isMultiple(of: 2) { Spacer(minLength: 42) }; Text(message[string: "body"]).font(.subheadline).foregroundStyle(index.isMultiple(of: 2) ? AFTheme.paper : AFTheme.ink).padding(12).background(index.isMultiple(of: 2) ? AFTheme.graphite : AFTheme.paper).clipShape(RoundedRectangle(cornerRadius: 16, style: .continuous)); if !index.isMultiple(of: 2) { Spacer(minLength: 42) } } } }.padding(20) }; HStack(spacing: 9) { TextField("Scrie un mesaj…", text: $draft).padding(12).background(AFTheme.paper).clipShape(Capsule()); Button { send(id) } label: { Image(systemName: "arrow.up").font(.headline.bold()).foregroundStyle(AFTheme.paper).frame(width: 45, height: 45).background(AFTheme.graphite).clipShape(Circle()) }.disabled(draft.trimmed == nil) }.padding(12).background(.ultraThinMaterial) } }
    private func loadConversations() async { do { conversations = try await app.api.call("conversations")["conversations"]?.array?.compactMap(\.object) ?? [] } catch { self.error = error.localizedDescription } }
    private func loadMessages(_ id: Int) async { do { messages = try await app.api.call("messages", payload: ["conversationId": .number(Double(id))])["messages"]?.array?.compactMap(\.object) ?? [] } catch { self.error = error.localizedDescription } }
    private func send(_ id: Int) { let text = draft; Task { do { _ = try await app.api.call("send_message", payload: ["conversationId": .number(Double(id)), "message": .string(text)]); draft = ""; await loadMessages(id) } catch { self.error = error.localizedDescription } } }
}
