import SwiftUI
import PhotosUI

struct SellerEntryView: View {
    @EnvironmentObject private var app: AppContainer
    @State private var profile = [String: JSONValue]()
    @State private var loading = true
    @State private var message = ""
    let open: (Route) -> Void
    var body: some View { AFScreen { ScrollView { VStack(alignment: .leading, spacing: 20) { Text("Vinde cu AutoFans").font(.system(size: 31, weight: .bold, design: .rounded)).foregroundStyle(AFTheme.ink); Text("Anunțurile, fotografiile și conversațiile tale — într-un singur loc.").foregroundStyle(AFTheme.muted)
        ZStack(alignment: .bottomLeading) { AFBrandImage(name: "card_selling", ext: "jpg").frame(height: 210).clipped().overlay(LinearGradient(colors: [.clear, AFTheme.graphite.opacity(0.77)], startPoint: .top, endPoint: .bottom)); VStack(alignment: .leading, spacing: 5) { Text(profile[string: "role"] == "seller" ? "Spațiul tău de vânzare" : "Pregătit să vinzi?").font(.title2.weight(.bold)).foregroundStyle(.white); Text(profile[string: "role"] == "seller" ? "Gestionează-ți stocul cu ușurință." : "Creează un profil de seller în câteva secunde.").font(.subheadline).foregroundStyle(.white.opacity(0.78)) }.padding(18) }.clipShape(RoundedRectangle(cornerRadius: 26, style: .continuous))
        if loading { AFSkeleton().frame(height: 160) }
        else if profile[string: "role"] == "seller" { sellerActions }
        else { buyerUpgrade }
        if !message.isEmpty { Text(message).font(.footnote.weight(.semibold)).foregroundStyle(AFTheme.muted).frame(maxWidth: .infinity) }
    }.padding(20) } }.navigationTitle("Vinde").task { await load() } }
    private var sellerActions: some View { VStack(spacing: 12) { AFCard { VStack(alignment: .leading, spacing: 10) { Label(profile[bool: "is_verified"] ? "Vânzător verificat" : "Profil de seller", systemImage: profile[bool: "is_verified"] ? "checkmark.seal.fill" : "person.crop.circle.badge.plus").font(.headline.weight(.bold)).foregroundStyle(profile[bool: "is_verified"] ? .green : AFTheme.ink); Text(profile[bool: "is_verified"] ? "Profilul tău inspiră încredere." : "Solicită verificarea pentru mai multă încredere.").font(.subheadline).foregroundStyle(AFTheme.muted); if !profile[bool: "is_verified"] { Button("Solicită verificarea") { call("request_seller_verification") }.font(.subheadline.weight(.bold)).foregroundStyle(AFTheme.gold) } } }; Button { open(.listingEditor(nil)) } label: { Label("Publică un anunț nou", systemImage: "plus") }.buttonStyle(AFGoldButton()); HStack(spacing: 12) { Button("Anunțurile mele") { open(.sellerListings) }.buttonStyle(AFPrimaryButton()); Button("Dashboard") { open(.sellerDashboard) }.buttonStyle(AFPrimaryButton()) } } }
    private var buyerUpgrade: some View { AFCard { VStack(alignment: .leading, spacing: 14) { Text("Transformă-ți contul în seller").font(.title3.weight(.bold)).foregroundStyle(AFTheme.ink); Text("Publică anunțuri, încarcă fotografii și răspunde cumpărătorilor din aplicație.").font(.subheadline).foregroundStyle(AFTheme.muted); Button("Devino vânzător") { call("promote_seller") }.buttonStyle(AFGoldButton()) } } }
    private func load() async { defer { loading = false }; do { profile = try await app.api.call("account")["profile"]?.object ?? [:] } catch { message = error.localizedDescription } }
    private func call(_ operation: String) { Task { do { _ = try await app.api.call(operation); message = operation == "promote_seller" ? "Contul tău este acum seller." : "Solicitarea a fost trimisă."; await load() } catch { message = error.localizedDescription } } }
}

struct SellerListingsView: View {
    @EnvironmentObject private var app: AppContainer
    @State private var listings = [[String: JSONValue]]()
    @State private var error = ""
    let open: (Route) -> Void
    var body: some View { List { if !error.isEmpty { Text(error).foregroundStyle(.red) }; ForEach(Array(listings.enumerated()), id: \.offset) { _, listing in VStack(alignment: .leading, spacing: 6) { Text(listing[string: "title"]).font(.headline); Text("\(listing[string: "price"]) \(listing[string: "currency"])").foregroundStyle(.blue); Text(listing[string: "status"]).font(.footnote).foregroundStyle(.secondary); HStack { if let id = listing[int: "id"] { Button("Editează") { open(.listingEditor(id)) }; Button(listing[string: "status"] == "draft" ? "Publică" : "Draft") { updateStatus(id, listing[string: "status"] == "draft" ? "published" : "draft") }; Button("Șterge", role: .destructive) { delete(id) } } } } } }.navigationTitle("Anunțurile mele").task { await load() }.refreshable { await load() } }
    private func load() async { do { listings = try await app.api.call("seller_listings")["listings"]?.array?.compactMap(\.object) ?? [] } catch { self.error = error.localizedDescription } }
    private func updateStatus(_ id: Int, _ status: String) { Task { do { _ = try await app.api.call("set_listing_status", payload: ["id": .number(Double(id)), "status": .string(status)]); await load() } catch { self.error = error.localizedDescription } } }
    private func delete(_ id: Int) { Task { do { _ = try await app.api.call("delete_listing", payload: ["id": .number(Double(id))]); await load() } catch { self.error = error.localizedDescription } } }
}

struct ListingEditorView: View {
    @EnvironmentObject private var app: AppContainer
    @Environment(\.dismiss) private var dismiss
    let id: Int?
    @State private var title = ""; @State private var description = ""; @State private var make = ""; @State private var model = ""; @State private var year = ""; @State private var mileage = ""; @State private var price = ""; @State private var city = ""; @State private var county = ""; @State private var fuel = "petrol"; @State private var transmission = "manual"; @State private var vin = ""; @State private var bodyType = ""; @State private var engineSize = ""; @State private var power = ""; @State private var doors = ""; @State private var seats = ""; @State private var owners = ""; @State private var features = ""; @State private var serviceHistory = false; @State private var images = [String](); @State private var pickerItems = [PhotosPickerItem](); @State private var message = ""; @State private var saving = false
    var body: some View { Form { Section("Informații") { field("Titlu", $title); field("Marcă", $make); field("Model", $model); numeric("An", $year); numeric("Kilometraj", $mileage); numeric("Preț", $price); field("Oraș", $city); field("Județ", $county); TextEditor(text: $description).frame(minHeight: 110).overlay(alignment: .topLeading) { if description.isEmpty { Text("Descriere (minim 50 caractere)").foregroundStyle(.tertiary).padding(.top, 8) } } }
        Section("Specificații") { field("Combustibil", $fuel); field("Transmisie", $transmission); field("VIN (opțional)", $vin); field("Caroserie", $bodyType); numeric("Motor (L)", $engineSize); numeric("Putere CP", $power); numeric("Uși", $doors); numeric("Locuri", $seats); numeric("Proprietari", $owners); field("Dotări, separate prin virgulă", $features); Toggle("Istoric de service disponibil", isOn: $serviceHistory) }
        Section("Fotografii") { PhotosPicker(selection: $pickerItems, maxSelectionCount: max(0, 15 - images.count), matching: .images) { Label("Adaugă fotografii (\(images.count)/15)", systemImage: "photo.on.rectangle") }; ForEach(images.indices, id: \.self) { index in HStack { Text(index == 0 ? "Poză principală" : "Poză \(index + 1)"); Spacer(); Button("↑") { move(index, index - 1) }.disabled(index == 0); Button("↓") { move(index, index + 1) }.disabled(index == images.count - 1); Button("Elimină", role: .destructive) { images.remove(at: index) } } } }
        if !message.isEmpty { Section { Text(message).foregroundStyle(.red) } }; Section { Button("Salvează draft") { save("draft") }.disabled(saving); Button(id == nil ? "Publică" : "Salvează și publică") { save("published") }.disabled(saving || images.isEmpty).buttonStyle(.borderedProminent) }
    }.navigationTitle(id == nil ? "Anunț nou" : "Editează anunț").task { await load() }.onChange(of: pickerItems) { _, items in Task { await upload(items) } } }
    private func field(_ title: String, _ value: Binding<String>) -> some View { TextField(title, text: value) }
    private func numeric(_ title: String, _ value: Binding<String>) -> some View { TextField(title, text: value).keyboardType(.decimalPad) }
    private func load() async { guard let id else { return }; do { let data = try await app.api.call("seller_listing", payload: ["id": .number(Double(id))]); guard let listing = data["listing"]?.object else { return }; title = listing[string: "title"]; description = listing[string: "description"]; make = listing[string: "make"]; model = listing[string: "model"]; year = listing[string: "year"]; mileage = listing[string: "mileage"]; price = listing[string: "price"]; city = listing[string: "city"]; county = listing[string: "county"]; fuel = listing[string: "fuel_type"]; transmission = listing[string: "transmission"]; vin = listing[string: "vin"]; bodyType = listing[string: "body_type"]; engineSize = listing[string: "engine_size"]; power = listing[string: "power"]; doors = listing[string: "doors"]; seats = listing[string: "seats"]; owners = listing[string: "owners"]; serviceHistory = listing[bool: "service_history"]; features = listing["features"]?.array?.compactMap(\.string).joined(separator: ", ") ?? ""; images = listing["images"]?.array?.compactMap { $0.object?[string: "path"] }.filter { !$0.isEmpty } ?? [] } catch { message = error.localizedDescription } }
    private func upload(_ items: [PhotosPickerItem]) async { for item in items { do { guard let data = try await item.loadTransferable(type: Data.self), let image = UIImage(data: data) else { continue }; images.append(try await app.api.uploadListingImage(image)) } catch { message = error.localizedDescription } }; pickerItems = [] }
    private func move(_ from: Int, _ to: Int) { guard images.indices.contains(to) else { return }; let image = images.remove(at: from); images.insert(image, at: to) }
    private func save(_ status: String) { saving = true; Task { defer { saving = false }; var payload: [String: JSONValue] = ["status": .string(status), "title": .string(title), "description": .string(description), "make": .string(make), "model": .string(model), "year": .number(Double(year) ?? 0), "mileage": .number(Double(mileage) ?? -1), "price": .number(Double(price) ?? 0), "city": .string(city), "county": .string(county), "fuel_type": .string(fuel), "transmission": .string(transmission), "currency": .string("EUR"), "vin": .string(vin), "body_type": .string(bodyType), "service_history": .bool(serviceHistory), "features": .array(features.split(separator: ",").map { .string($0.trimmingCharacters(in: .whitespaces)) }), "images": .array(images.map { .object(["path": .string($0)]) })]; if let id { payload["id"] = .number(Double(id)) }; for (key, value) in [("engine_size", engineSize), ("power", power), ("doors", doors), ("seats", seats), ("owners", owners)] { if let number = Double(value) { payload[key] = .number(number) } }; do { _ = try await app.api.call("save_listing", payload: payload); dismiss() } catch { message = error.localizedDescription } } }
}

struct SellerDashboardView: View { @EnvironmentObject private var app: AppContainer; @State private var data = [String: JSONValue](); @State private var error = ""
    var body: some View { List { if !error.isEmpty { Text(error).foregroundStyle(.red) }; if let profile = data["profile"]?.object { Section("Cont") { Text(profile[string: "role"]); Text(profile[bool: "is_verified"] ? "Vânzător verificat" : "Verificare în așteptare") } }; Section("Performanța anunțurilor") { ForEach(Array((data["metrics"]?.array ?? []).indices), id: \.self) { index in let metric = (data["metrics"]?.array?[index].object) ?? [:]; VStack(alignment: .leading) { Text(metric[string: "title"]); Text("Vizualizări: \(metric[string: "view_count"]) · Favorite: \(metric[string: "favorite_count"])").foregroundStyle(.secondary) } } } }.navigationTitle("Dashboard seller").task { do { data = try await app.api.call("seller_dashboard") } catch { self.error = error.localizedDescription } } }
}

struct SellerProfileView: View { @EnvironmentObject private var app: AppContainer; @State private var data = [String: JSONValue](); @State private var error = ""; @State private var review = ""; @State private var rating = 5; let sellerID: String; let open: (Route) -> Void
    var body: some View { List { if !error.isEmpty { Text(error).foregroundStyle(.red) }; if let profile = data["profile"]?.object { Section { Text(profile[string: "display_name"]).font(.title3.bold()); if profile[bool: "is_verified"] { Label("Vânzător verificat", systemImage: "checkmark.seal.fill").foregroundStyle(.green) }; if !profile[string: "phone"].isEmpty { Text(profile[string: "phone"]) } } }; Section("Anunțuri") { ForEach(Array((data["listings"]?.array ?? []).indices), id: \.self) { index in let listing = (data["listings"]?.array?[index].object) ?? [:]; Button(listing[string: "title"]) { if let slug = listing["slug"]?.string { open(.listing(slug)) } } } }; Section("Recenzii") { ForEach(Array((data["reviews"]?.array ?? []).indices), id: \.self) { index in let row = (data["reviews"]?.array?[index].object) ?? [:]; VStack(alignment: .leading) { Text("\(row[string: "rating"])/5 ★"); Text(row[string: "comment"]) } }; Stepper("Rating: \(rating)", value: $rating, in: 1...5); TextField("Scrie o recenzie (minim 10 caractere)", text: $review); Button("Trimite recenzia") { Task { do { _ = try await app.api.call("save_review", payload: ["sellerId": .string(sellerID), "rating": .number(Double(rating)), "comment": .string(review)]); review = ""; await load() } catch { self.error = error.localizedDescription } } }.disabled(review.count < 10) } }.navigationTitle("Vânzător").task { await load() } }
    private func load() async { do { data = try await app.api.call("seller_profile", payload: ["sellerId": .string(sellerID)]) } catch { self.error = error.localizedDescription } }
}
