-- Dealer stock imports stay separate from public listings until every row is
-- complete and explicitly published by the seller.
create table if not exists public.dealer_csv_imports (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  file_name text not null check (char_length(file_name) between 1 and 255),
  total_rows integer not null default 0 check (total_rows >= 0),
  imported_count integer not null default 0 check (imported_count >= 0),
  invalid_count integer not null default 0 check (invalid_count >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.dealer_csv_import_rows (
  id bigint generated by default as identity primary key,
  import_id uuid not null references public.dealer_csv_imports(id) on delete cascade,
  row_number integer not null check (row_number > 1),
  external_stock_id text,
  listing_id bigint references public.listings(id) on delete set null,
  status text not null check (status in ('imported', 'invalid')),
  errors jsonb not null default '[]'::jsonb,
  raw_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.listings
  add column if not exists dealer_import_id uuid references public.dealer_csv_imports(id) on delete set null,
  add column if not exists dealer_external_stock_id text;

create index if not exists dealer_csv_imports_owner_created_idx
  on public.dealer_csv_imports (owner_id, created_at desc);

create index if not exists dealer_csv_import_rows_import_idx
  on public.dealer_csv_import_rows (import_id, row_number);

create index if not exists listings_dealer_import_idx
  on public.listings (dealer_import_id);

create unique index if not exists listings_owner_dealer_stock_id_unique
  on public.listings (owner_id, dealer_external_stock_id)
  where dealer_external_stock_id is not null;

alter table public.dealer_csv_imports enable row level security;
alter table public.dealer_csv_import_rows enable row level security;

create policy "dealers read own csv imports"
  on public.dealer_csv_imports for select to authenticated
  using (owner_id = auth.uid());

create policy "dealers create own csv imports"
  on public.dealer_csv_imports for insert to authenticated
  with check (
    owner_id = auth.uid()
    and exists (select 1 from public.profiles where id = auth.uid() and role = 'seller')
  );

create policy "dealers update own csv imports"
  on public.dealer_csv_imports for update to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

create policy "dealers delete own csv imports"
  on public.dealer_csv_imports for delete to authenticated
  using (owner_id = auth.uid());

create policy "dealers read own csv import rows"
  on public.dealer_csv_import_rows for select to authenticated
  using (
    exists (
      select 1 from public.dealer_csv_imports imports
      where imports.id = dealer_csv_import_rows.import_id and imports.owner_id = auth.uid()
    )
  );

create policy "dealers create own csv import rows"
  on public.dealer_csv_import_rows for insert to authenticated
  with check (
    exists (
      select 1 from public.dealer_csv_imports imports
      where imports.id = dealer_csv_import_rows.import_id and imports.owner_id = auth.uid()
    )
  );

grant select, insert, update, delete on public.dealer_csv_imports to authenticated;
grant select, insert on public.dealer_csv_import_rows to authenticated;
grant usage, select on sequence public.dealer_csv_import_rows_id_seq to authenticated;
