-- Track real listing activity for seller statistics.
create table if not exists public.listing_views (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  visitor_id uuid references auth.users(id) on delete set null,
  session_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.listing_contacts (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  visitor_id uuid references auth.users(id) on delete set null,
  contact_type text not null default 'seller',
  created_at timestamptz not null default now()
);

create index if not exists idx_listing_views_listing on public.listing_views(listing_id);
create index if not exists idx_listing_contacts_listing on public.listing_contacts(listing_id);

alter table public.listing_views enable row level security;
alter table public.listing_contacts enable row level security;

drop policy if exists "anyone can record listing views" on public.listing_views;
create policy "anyone can record listing views"
on public.listing_views for insert
to anon, authenticated
with check (exists (select 1 from public.listings where id = listing_id and status = 'published'));

drop policy if exists "anyone can record listing contacts" on public.listing_contacts;
create policy "anyone can record listing contacts"
on public.listing_contacts for insert
to anon, authenticated
with check (exists (select 1 from public.listings where id = listing_id and status = 'published'));

drop policy if exists "owners can read listing views" on public.listing_views;
create policy "owners can read listing views"
on public.listing_views for select
to authenticated
using (exists (select 1 from public.listings where listings.id = listing_views.listing_id and listings.owner_id = auth.uid()));

drop policy if exists "owners can read listing contacts" on public.listing_contacts;
create policy "owners can read listing contacts"
on public.listing_contacts for select
to authenticated
using (exists (select 1 from public.listings where listings.id = listing_contacts.listing_id and listings.owner_id = auth.uid()));
