-- Buyer safety: authenticated users can flag another seller's listing for review.
create table if not exists public.listing_reports (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in ('fraud', 'incorrect_details', 'duplicate', 'offensive_content', 'other')),
  details text not null default '' check (char_length(details) <= 1000),
  status text not null default 'open' check (status in ('open', 'reviewed', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists listing_reports_open_created_at_idx
  on public.listing_reports (status, created_at desc);

create unique index if not exists listing_reports_one_open_per_reason_idx
  on public.listing_reports (listing_id, reporter_id, reason)
  where status = 'open';

alter table public.listing_reports enable row level security;

drop policy if exists "reporters can create listing reports" on public.listing_reports;
create policy "reporters can create listing reports"
  on public.listing_reports for insert to authenticated
  with check (
    reporter_id = auth.uid()
    and exists (
      select 1 from public.listings
      where listings.id = listing_reports.listing_id
        and listings.owner_id <> auth.uid()
        and listings.status = 'published'
    )
  );

drop policy if exists "reporters can read their listing reports" on public.listing_reports;
create policy "reporters can read their listing reports"
  on public.listing_reports for select to authenticated
  using (reporter_id = auth.uid());
